networks:
  app:

services:
  ai-service:
    build:
      dockerfile: ai-service/Dockerfile
    env_file:
      - .env
    networks:
      - app
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
  backend:
    build:
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    networks:
      - app
    ports:
      - "8080:8080"
    depends_on:
      ai-service:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./data/cert.crt:/etc/ssl/certs/cert.crt
      - ./data/cert.key:/etc/ssl/certs/cert.key
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app
    depends_on:
      - backend